# Generated by Django 6.0.5 on 2026-05-24 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('users', '0002_customuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by', to='collection.record'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shelf',
            field=models.ManyToManyField(blank=True, related_name='shelved_by', to='collection.record'),
        ),
    ]
