# Generated by Django 6.0.5 on 2026-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('users', '0003_customuser_favorite_record_customuser_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('default', 'Default Dark'), ('midnight', 'Midnight Blue'), ('sunset', 'Sunset Orange'), ('forest', 'Forest Green'), ('berry', 'Berry Purple')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='collection.record'),
        ),
    ]
