# Generated by Django 6.0.5 on 2026-05-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shelf_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
