# Generated by Django 6.0.5 on 2026-05-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('ADD', 'added to their collection'), ('SHELF', 'placed on their shelf'), ('FAVORITE', 'set as their Top Spin'), ('WISHLIST', 'added to their wishlist')], max_length=15),
        ),
    ]
