# Generated by Django 6.0.5 on 2026-05-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark (Default)'), ('light', 'Light'), ('system', 'System Default')], default='dark', max_length=10),
        ),
    ]
