# Generated by Django 6.0.5 on 2026-05-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_last_username_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tagline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
