# Generated by Django 6.0.5 on 2026-05-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_artist_artist_name_lower_idx_and_more'),
        ('users', '0010_customuser_tagline'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-created_at'], name='activity_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', '-created_at'], name='activity_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', '-created_at'], name='activity_type_created_idx'),
        ),
    ]
