# Generated by Django 6.0.5 on 2026-05-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarding_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarding_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarding_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
