# Generated by Django 6.0.5 on 2026-05-24 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='rating',
            field=models.IntegerField(blank=True, help_text='1 to 5 star rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='variant_description',
            field=models.CharField(blank=True, help_text='e.g., 180g Black, Pink Marble Splatter, 1973 Original Pressing', max_length=255, null=True),
        ),
    ]
