# Generated by Django 6.0.5 on 2026-05-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collectionitem_rating_collectionitem_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
