# Generated by Django 6.0.5 on 2026-05-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_record_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='discogs_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='profile_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
