# Generated by Django 6.0.5 on 2026-05-25 20:26

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_artist_discogs_id_artist_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='artist_name_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['user', '-date_added'], name='collection_user_added_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['record', '-date_added'], name='collection_record_added_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['rating'], name='collection_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['title'], name='record_title_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['artist', 'title'], name='record_artist_title_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['-year'], name='record_year_desc_idx'),
        ),
    ]
